export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const EDIT_CARD = 'EDIT_CARD';
export const UPDATE_CARD = 'UPDATE_CARD';
export const DELETE_ALL = 'DELETE_ALL';

export const USER_REGISTER = 'USER_REGISTER';
export const STASH_PASSPHRASE = 'STASH_PASSPHRASE';
export const SET_CLEAR_MASTERKEY = 'SET_CLEAR_MASTERKEY';
export const REMOVE_CLEAR_MASTERKEY = 'REMOVE_CLEAR_MASTERKEY';

export const SERVER_HOST_SET = "SERVER_HOST_SET"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"

export const SESSION_OPEN_REQUEST = "SESSION_OPEN_REQUEST"
export const SESSION_OPEN_SUCCESS = "SESSION_OPEN_SUCCESS"
export const SESSION_OPEN_FAILURE = "SESSION_OPEN_FAILURE"

export const SESSION_CLOSE_REQUEST = "SESSION_CLOSE_REQUEST"
export const SESSION_CLOSE_SUCCESS = "SESSION_CLOSE_SUCCESS"
export const SESSION_CLOSE_FAILURE = "SESSION_CLOSE_FAILURE"

export const SECRET_CHANGE_REQUEST = "SECRET_CHANGE_REQUEST"
export const SECRET_CHANGE_SUCCESS = "SECRET_CHANGE_SUCCESS"
export const SECRET_CHANGE_FAILURE = "SECRET_CHANGE_FAILURE"

export const CARD_ADD_REQUEST = "CARD_ADD_REQUEST"
export const CARD_ADD_SUCCESS = "CARD_ADD_SUCCESS"
export const CARD_ADD_FAILURE = "CARD_ADD_FAILURE"

export const CARD_UPDATE_REQUEST = "CARD_UPDATE_REQUEST"
export const CARD_UPDATE_SUCCESS = "CARD_UPDATE_SUCCESS"
export const CARD_UPDATE_FAILURE = "CARD_UPDATE_FAILURE"

export const CARD_DELETE_REQUEST = "CARD_DELETE_REQUEST"
export const CARD_DELETE_SUCCESS = " CARD_DELETE_SUCCESS"
export const CARD_DELETE_FAILURE = "CARD_DELETE_FAILURE"

export const CARD_FETCH_REQUEST = "CARD_FETCH_REQUEST"
export const CARD_FETCH_SUCCESS = "CARD_FETCH_SUCCESS"
export const CARD_FETCH_FAILURE = "CARD_FETCH_FAILURE"

export const CARDS_LIST_REQUEST = "CARDS_LIST_REQUEST"
export const CARDS_LIST_SUCCESS = "CARDS_LIST_SUCCESS"
export const CARDS_LIST_FAILURE = "CARDS_LIST_FAILURE"

export const WKEY_FETCH_REQUEST = "WKEY_FETCH_REQUEST"
export const WKEY_FETCH_SUCCESS = "WKEY_FETCH_SUCCESS"
export const WKEY_FETCH_FAILURE = "WKEY_FETCH_FAILURE"
